version: '3'

env:
  PROJECT: clarum-agent
  VERSION: 1.0.0-snapshot

tasks:
  version:
    cmds:
      - echo $VERSION

  build:dev:
    cmds:
      - go build -o ./builds/{{.PROJECT}}-{{.VERSION}}

  build:prod:
    deps: [ api:generate, build:dev ]

  api:generate:
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        api/**/*.proto

  test:
    cmds:
      - go test ./...
