// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: api/cmd/clarum-cmd.proto

package cmd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CmdServiceClient is the client API for CmdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmdServiceClient interface {
	InitEndpoint(ctx context.Context, in *InitEndpointRequest, opts ...grpc.CallOption) (*InitEndpointResponse, error)
	ShutdownEndpoint(ctx context.Context, in *ShutdownEndpointRequest, opts ...grpc.CallOption) (*ShutdownEndpointResponse, error)
}

type cmdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCmdServiceClient(cc grpc.ClientConnInterface) CmdServiceClient {
	return &cmdServiceClient{cc}
}

func (c *cmdServiceClient) InitEndpoint(ctx context.Context, in *InitEndpointRequest, opts ...grpc.CallOption) (*InitEndpointResponse, error) {
	out := new(InitEndpointResponse)
	err := c.cc.Invoke(ctx, "/CmdService/InitEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdServiceClient) ShutdownEndpoint(ctx context.Context, in *ShutdownEndpointRequest, opts ...grpc.CallOption) (*ShutdownEndpointResponse, error) {
	out := new(ShutdownEndpointResponse)
	err := c.cc.Invoke(ctx, "/CmdService/ShutdownEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdServiceServer is the server API for CmdService service.
// All implementations must embed UnimplementedCmdServiceServer
// for forward compatibility
type CmdServiceServer interface {
	InitEndpoint(context.Context, *InitEndpointRequest) (*InitEndpointResponse, error)
	ShutdownEndpoint(context.Context, *ShutdownEndpointRequest) (*ShutdownEndpointResponse, error)
	mustEmbedUnimplementedCmdServiceServer()
}

// UnimplementedCmdServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCmdServiceServer struct {
}

func (UnimplementedCmdServiceServer) InitEndpoint(context.Context, *InitEndpointRequest) (*InitEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitEndpoint not implemented")
}
func (UnimplementedCmdServiceServer) ShutdownEndpoint(context.Context, *ShutdownEndpointRequest) (*ShutdownEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownEndpoint not implemented")
}
func (UnimplementedCmdServiceServer) mustEmbedUnimplementedCmdServiceServer() {}

// UnsafeCmdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CmdServiceServer will
// result in compilation errors.
type UnsafeCmdServiceServer interface {
	mustEmbedUnimplementedCmdServiceServer()
}

func RegisterCmdServiceServer(s grpc.ServiceRegistrar, srv CmdServiceServer) {
	s.RegisterService(&CmdService_ServiceDesc, srv)
}

func _CmdService_InitEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServiceServer).InitEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CmdService/InitEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServiceServer).InitEndpoint(ctx, req.(*InitEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmdService_ShutdownEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServiceServer).ShutdownEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CmdService/ShutdownEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServiceServer).ShutdownEndpoint(ctx, req.(*ShutdownEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CmdService_ServiceDesc is the grpc.ServiceDesc for CmdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CmdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CmdService",
	HandlerType: (*CmdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitEndpoint",
			Handler:    _CmdService_InitEndpoint_Handler,
		},
		{
			MethodName: "ShutdownEndpoint",
			Handler:    _CmdService_ShutdownEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/cmd/clarum-cmd.proto",
}
