// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: api/cmd/clarum-cmd.proto

package cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WarmupMillis  int32    `protobuf:"varint,2,opt,name=warmup_millis,json=warmupMillis,proto3" json:"warmup_millis,omitempty"`
	CmdComponents []string `protobuf:"bytes,3,rep,name=cmd_components,json=cmdComponents,proto3" json:"cmd_components,omitempty"`
}

func (x *InitEndpointRequest) Reset() {
	*x = InitEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cmd_clarum_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEndpointRequest) ProtoMessage() {}

func (x *InitEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cmd_clarum_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEndpointRequest.ProtoReflect.Descriptor instead.
func (*InitEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_cmd_clarum_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *InitEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitEndpointRequest) GetWarmupMillis() int32 {
	if x != nil {
		return x.WarmupMillis
	}
	return 0
}

func (x *InitEndpointRequest) GetCmdComponents() []string {
	if x != nil {
		return x.CmdComponents
	}
	return nil
}

type InitEndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *InitEndpointResponse) Reset() {
	*x = InitEndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cmd_clarum_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEndpointResponse) ProtoMessage() {}

func (x *InitEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cmd_clarum_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEndpointResponse.ProtoReflect.Descriptor instead.
func (*InitEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_cmd_clarum_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *InitEndpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShutdownEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ShutdownEndpointRequest) Reset() {
	*x = ShutdownEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cmd_clarum_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownEndpointRequest) ProtoMessage() {}

func (x *ShutdownEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cmd_clarum_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownEndpointRequest.ProtoReflect.Descriptor instead.
func (*ShutdownEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_cmd_clarum_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *ShutdownEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ShutdownEndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ShutdownEndpointResponse) Reset() {
	*x = ShutdownEndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cmd_clarum_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownEndpointResponse) ProtoMessage() {}

func (x *ShutdownEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cmd_clarum_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownEndpointResponse.ProtoReflect.Descriptor instead.
func (*ShutdownEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_cmd_clarum_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownEndpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_cmd_clarum_cmd_proto protoreflect.FileDescriptor

var file_api_cmd_clarum_cmd_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6c, 0x61, 0x72, 0x75, 0x6d,
	0x2d, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x13, 0x49, 0x6e,
	0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x61, 0x72, 0x6d, 0x75, 0x70, 0x5f,
	0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x61,
	0x72, 0x6d, 0x75, 0x70, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6d,
	0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6d, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x2c, 0x0a, 0x14, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x2d, 0x0a, 0x17, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30,
	0x0a, 0x18, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x96, 0x01, 0x0a, 0x0a, 0x43, 0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3d, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x14, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x10, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x18, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6c, 0x61, 0x72, 0x75,
	0x6d, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_cmd_clarum_cmd_proto_rawDescOnce sync.Once
	file_api_cmd_clarum_cmd_proto_rawDescData = file_api_cmd_clarum_cmd_proto_rawDesc
)

func file_api_cmd_clarum_cmd_proto_rawDescGZIP() []byte {
	file_api_cmd_clarum_cmd_proto_rawDescOnce.Do(func() {
		file_api_cmd_clarum_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_cmd_clarum_cmd_proto_rawDescData)
	})
	return file_api_cmd_clarum_cmd_proto_rawDescData
}

var file_api_cmd_clarum_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_cmd_clarum_cmd_proto_goTypes = []interface{}{
	(*InitEndpointRequest)(nil),      // 0: InitEndpointRequest
	(*InitEndpointResponse)(nil),     // 1: InitEndpointResponse
	(*ShutdownEndpointRequest)(nil),  // 2: ShutdownEndpointRequest
	(*ShutdownEndpointResponse)(nil), // 3: ShutdownEndpointResponse
}
var file_api_cmd_clarum_cmd_proto_depIdxs = []int32{
	0, // 0: CmdService.InitEndpoint:input_type -> InitEndpointRequest
	2, // 1: CmdService.ShutdownEndpoint:input_type -> ShutdownEndpointRequest
	1, // 2: CmdService.InitEndpoint:output_type -> InitEndpointResponse
	3, // 3: CmdService.ShutdownEndpoint:output_type -> ShutdownEndpointResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cmd_clarum_cmd_proto_init() }
func file_api_cmd_clarum_cmd_proto_init() {
	if File_api_cmd_clarum_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_cmd_clarum_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cmd_clarum_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitEndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cmd_clarum_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cmd_clarum_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownEndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_cmd_clarum_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cmd_clarum_cmd_proto_goTypes,
		DependencyIndexes: file_api_cmd_clarum_cmd_proto_depIdxs,
		MessageInfos:      file_api_cmd_clarum_cmd_proto_msgTypes,
	}.Build()
	File_api_cmd_clarum_cmd_proto = out.File
	file_api_cmd_clarum_cmd_proto_rawDesc = nil
	file_api_cmd_clarum_cmd_proto_goTypes = nil
	file_api_cmd_clarum_cmd_proto_depIdxs = nil
}
