version: '3'

env:
  PROJECT: clarum-agent
  VERSION: 1.0.0-snapshot

tasks:
  version:
    cmds:
      - echo $VERSION

  build:
    deps: [ api:generate]
    cmds:
      - go build -o ./builds/{{.PROJECT}}-{{.VERSION}}

  api:generate:
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        interface/grpc/agent/internal/api/commands/cmd/cmd.proto \
        interface/grpc/agent/internal/api/commands/http/http.proto \
        interface/grpc/agent/internal/api/agent.proto

  test:
    cmds:
      - go test ./...
